MAN5PAGES = opennhrp.conf.5
MAN8PAGES = opennhrp.8 opennhrpctl.8 opennhrp-script.8

install::
	$(INSTALLDIR) $(DESTDIR)$(MANDIR)/man5 $(DESTDIR)$(MANDIR)/man8
	$(INSTALL) $(MAN5PAGES) $(DESTDIR)$(MANDIR)/man5
	$(INSTALL) $(MAN8PAGES) $(DESTDIR)$(MANDIR)/man8
