.TH OPENNHRP-SCRIPT 8 "16 November 2007" "" "OpenNHRP Documentation"

.SH NAME
opennhrp-script \- NHRP peer configuration script

.SH DESCRIPTION
NHRP peer configuration script is used invoked by
.BR opennhrp (8).
.PP
This script can be used to establish a direct NBMA peer to peer connection
after NHRP Resolution Reply has been received, but prior to injecting the
peer address to kernel neighbor table. This could be to insert firewall rules
allowing the traffic and/or establishing an IPsec connection (or some other
secure communication channel). The script is also called when the cached peer
information expires.

.SH OPERATION
When
.B opennhrp
needs to invoke the peer configuration script, it defines a set of variables
in the environment and then executes the script with exactly one argument.
The argument is set to the name of the reason why the script has been invoked.
The following reasons are currently defined:
.BR peer-up , " peer-down" , " route-up" " and " route-down .

.SH PEER-UP
A peer has been discovered (either by means of static configuration, dynamic
client registration or resolution reply arrival to initiate shortcut). This
hook is invoked right after the peer information is available, but before it
is injected to kernel ARP tables. If non-zero return value is returned, the
peer entry is marked as invalid and negative cached for short period of time.

.SH PEER-DOWN
A peer connection is about to be cleared. This can happend for dynamic client
registrations or cached information. Dynamic client registrations are teared
down when registration holding time expires (and no re-registration has
occured) or if it explicitely removed using Purge Request. Cached entries are
removed when holding time expires (and there has been no traffic to trigger
renewal of the peer address information) or when it is explicitely removed
with Purge Request.

.SH ROUTE-UP
In reply to resolution request we have received a shortcut route with
destination off the NBMA subnetwork. The script should insert appropriate
entry to kernel routing table.

.SH ROUTE-DOWN
The associated shortcut route information is no longer valid and should be
removed from kernel routing table.

.SH ENVIRONMENT
.B NHRP_TYPE
.RS
For peer-up and peer-down reasons this can be: \fBstatic\fR (configured
information), \fBdynamic\fR (client told us where he is) or \fBcached\fR
(resolved since we had packets going there).

For route-up and route-down reasons this is always defined as \fBroute\fR.
.RE

.B NHRP_DESTADDR
.RS
Destination protocol address. E.g. for NBMA GRE tunnels this is the IP address
assigned to the tunnel interface being used.
.RE

.B NHRP_DESTPREFIX
.RS
Subnet prefix length for destination protocol address.
.RE

.B NHRP_DESTNBMA
.RS
Defined only for \fBpeer-up\fR and \fBpeer-down\fR reasons. This contains the
NBMA address of the destination. E.g. for NBMA GRE this contains the public IP
of the peer.
.RE

.B NHRP_NEXTHOP
.RS
Defined only for \fBroute-up\fR and \fBroute-down\fR reasons. This is the
protocol address of the next hop to be used in routing.
.RE

.B NHRP_DESTIFACE
.RS
Name of the interface which belongs to the same subnet as destination
protocol address.
.RE

.SH "SEE ALSO"
.BR opennhrp (8)

.SH AUTHORS
Timo Teras <timo.teras@iki.fi>
