.TH OPENNHRP 8 "25 February 2008" "" "OpenNHRP Documentation"

.SH NAME
opennhrpctl \- opennhrp administrative control tool

.SH SYNOPSIS
.B opennhrpctl
.BI "[\-a " admin\-socket "]" " command " "[" "arguments..." "]"

.SH DESCRIPTION
.B opennhrpctl
is an utility to control
.BR opennhrp (8)
daemon operation. A UNIX socket is used for communication between
.B opennhrpctl
and
.BR opennhrp (8).
Administration priviledges for a non-root user can be granted by modifying
the permissions and ownership of the socket.

The following commands are available:

.BI show
.RS
Show contents of next hop cache (configured and resolved entries).
.RE

.BI flush
.RS
Clear all non-permanent entries from the cache.
.RE

.BI purge
.RS
Purge entries from NHRP cache: cached entries are removed and permanent
entries are forced down, up and finally reregistered. Following options can be
used to limit purging to only matching entries:

.BI nbma " nbma-address"
.RS
Purge only entries where the remote has NBMA address
.IR nbma-address .
.RE

.BI protocol " protocol-address" "[/" "prefix-length" "]"
.RS
Purge only entries where the remote has protocol address
.IR protocol-address " with prefix length " prefix-length .
Both specifiers must exactly for the entry to match.
.RE

.BI local-nbma " nbma-address"
.RS
Search entries only from local interface which owns the NBMA address
.IR nbma-address .
.RE

.BI local-protocol " protocol-address"
.RS
Search entries only from local interface which owns the protocol address
.IR protocol-address .
.RE

.RE

.SH FILES
.I /var/run/opennhrp.socket
.RS
.BR opennhrp "(8) control socket"
.RE

.SH "SEE ALSO"
.BR opennhrp (8)

.SH AUTHORS
Timo Teras <timo.teras@iki.fi>
