#!/bin/sh

case $1 in
peer-up)
	echo "Neighbor $NHRP_DESTADDR at $NHRP_DESTNBMA discovered"
	;;
peer-down)
	echo "Neighbor $NHRP_DESTADDR at $NHRP_DESTNBMA is gone"
	;;
route-up)
	echo "Route $NHRP_DESTADDR/$NHRP_DESTPREFIX is up"
	ip route del $NHRP_DESTADDR/$NHRP_DESTPREFIX
	ip route add $NHRP_DESTADDR/$NHRP_DESTPREFIX proto 42 via $NHRP_NEXTHOP
	ip route flush cache
	;;
route-down)
	echo "Route $NHRP_DESTADDR/$NHRP_DESTPREFIX is down"
	ip route del $NHRP_DESTADDR/$NHRP_DESTPREFIX proto 42
	ip route flush cache
	;;
esac

