#!/bin/sh

case $1 in
peer-up)
	echo "Neighbor $NHRP_DESTADDR at $NHRP_DESTNBMA discovered"
	MY_IP=`ip route get $NHRP_DESTNBMA | awk 'match($0, /src [^ ]*/) { print substr($0, RSTART+4, RLENGTH-4) };'`

	racoonctl establish-sa -w isakmp inet $MY_IP $NHRP_DESTNBMA || exit 1
	racoonctl establish-sa -w esp inet $MY_IP $NHRP_DESTNBMA gre || exit 1 
	;;
peer-down)
	echo "Neighbor $NHRP_DESTADDR at $NHRP_DESTNBMA is gone"
	racoonctl vpn-disconnect $NHRP_DESTADDR
	;;
route-up)
	echo "Route $NHRP_DESTADDR/$NHRP_DESTPREFIX is up"
	ip route del $NHRP_DESTADDR/$NHRP_DESTPREFIX
	ip route add $NHRP_DESTADDR/$NHRP_DESTPREFIX proto 42 via $NHRP_NEXTHOP
	ip route flush cache
	;;
route-down)
	echo "Route $NHRP_DESTADDR/$NHRP_DESTPREFIX is down"
	ip route del $NHRP_DESTADDR/$NHRP_DESTPREFIX proto 42
	ip route flush cache
	;;
esac

